# Clippy 配置
msrv = "1.70.0"
cognitive-complexity-threshold = 30
too-many-arguments-threshold = 10
type-complexity-threshold = 250
single-char-lifetime-names-threshold = 4
trivial-copy-size-limit = 128
pass-by-value-size-limit = 256
too-many-lines-threshold = 100
large-type-threshold = 200
vec-box-size-threshold = 4096
max-trait-bounds = 10
max-struct-bools = 3
max-fn-params-bools = 3
warn-on-all-wildcard-imports = false
disallowed-names = ["foo", "baz", "quux"]
blacklisted-names = ["foo", "baz", "quux"] 